%% Generated by lilypond-book.py
%% Options: [exampleindent=10.16\mm,fragment,indent=1.5\cm,line-width=160\mm,quote,relative=2]
\include "lilypond-book-preamble.ly"


% ****************************************************************
% Start cut-&-pastable-section
% ****************************************************************



\paper {
  indent = 1.5\cm
  line-width = 160\mm
  % offset the left padding, also add 1mm as lilypond creates cropped
  % images with a little space on the right
  line-width = #(- line-width (* mm  3.000000) (* mm 1))
  line-width = 160\mm - 2.0 * 10.16\mm
  % offset the left padding, also add 1mm as lilypond creates cropped
  % images with a little space on the right
  line-width = #(- line-width (* mm  3.000000) (* mm 1))
}

\layout {
  
}
\midi {
      \tempo 4 = 88
    }


\relative c'
{


% ****************************************************************
% ly snippet contents follows:
% ****************************************************************
\sourcefileline 926
<<
  \new Staff \with {
    instrumentName = #"Bass"
  }
  { \key aes \major \partial 4 f16 f' f, f' | bes,,1 | }
  \new Staff \with {
    instrumentName = \markup {
      \center-column { "Trombone"}
    }
  }
  \relative c' {\clef "bass" \key aes \major r4 | r4 <f, aes des ees>2~ <f aes des ees>8. <ees aes bes des>16 |}

\new Staff \with {
    instrumentName = \markup {
      \center-column { "Sax Bar"}
    }
  }
  \relative c' {\clef "treble" \key aes \major r4 | bes8 r8 bes8 r8 bes8 r8 bes8 r8 | ees8 r8 ees8 r8 ees8 r8 ees8 r8}


\new Staff \with {
    instrumentName = \markup {
      \center-column { "Clarinette"}
    }
  }
  \relative c' {\clef "treble" \key aes \major r4 | bes8 r8 bes8 r8 bes8 r8 bes8 r8 }

>>



% ****************************************************************
% end ly snippet
% ****************************************************************
}